favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5537634
  brandStrength: 0
  lightness: 0.5250896
  brandColors:
    - '#601013'
    - '#ffffff'
    - '#663b3d'
    - '#8c5b5e'
    - '#ccaaaa'
  rhythmicContrast: 0.5
typography_spectrum: 0.34168
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: Thoroughbred Polo Ponies
