name: Thoroughbred Polo Ponies
favicon: null
layout_spectrum: 0.36093
typography_spectrum: 0.34168
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#601013'
    - '#ffffff'
    - '#663b3d'
    - '#8c5b5e'
    - '#ccaaaa'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
